---
language: bash

os:
  - linux

services:
  - docker

#branches:
#  only:
#    - master

stages:
  - test
  - build_deploy

jobs:
  include:
    - stage: test
      name: "YamlLint"
      script: |
        docker run --rm -v $(pwd):/repo -it alpine:latest /bin/sh -c '
          cd /repo
          apk add --no-cache python3 py-pip
          pip install yamllint
          yamllint .
        '
    - stage: test
      name: "ShellCheck"
      script: |
        docker run --rm -v $(pwd):/repo -it alpine:latest /bin/sh -c '
          cd /repo
          apk add --no-cache shellcheck bash
          shellcheck ./*.sh
          shellcheck ./files/*.sh
        '
    - stage: build_deploy
      name: "Build Ubuntu and Deploy to GitHub Releases"
      script: ./build_in_docker.sh
      deploy:
        provider: releases
        api_key: "$GITHUB_TOKEN"
        file_glob: true
        file: "output/*"
        skip_cleanup: true
        on:
          tags: true
